### ISSUE TITLE
Add Logo

### ISSUE THREAD

**Issue by itsdfish** [itsdfish/SSMPlots.jl#4]
@DominiqueMakowski, I was wondering if you would be willing make a logo for this package based on the logo you made for SequentialSamplingModels.jl? I suppose this will eventually have the functionality to do it, but yours looks good and it's 90% done. So why reinvent the wheel?

**Comment by DominiqueMakowski** [comment]
I can give it a shot, but it'll be for next month as I'll be going on conference :)
